/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../pages/__root'
import { Route as NotFoundImport } from './../pages/not-found'
import { Route as LayoutImport } from './../pages/_layout'
import { Route as IndexImport } from './../pages/index'
import { Route as MoviesIndexImport } from './../pages/movies/index'
import { Route as MoviesCategoryImport } from './../pages/movies/$category'
import { Route as MovieIdImport } from './../pages/movie.$id'

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesIndexRoute = MoviesIndexImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesCategoryRoute = MoviesCategoryImport.update({
  id: '/movies/$category',
  path: '/movies/$category',
  getParentRoute: () => rootRoute,
} as any)

const MovieIdRoute = MovieIdImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdImport
      parentRoute: typeof rootRoute
    }
    '/movies/$category': {
      id: '/movies/$category'
      path: '/movies/$category'
      fullPath: '/movies/$category'
      preLoaderRoute: typeof MoviesCategoryImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/not-found': typeof NotFoundRoute
  '/movie/$id': typeof MovieIdRoute
  '/movies/$category': typeof MoviesCategoryRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/not-found': typeof NotFoundRoute
  '/movie/$id': typeof MovieIdRoute
  '/movies/$category': typeof MoviesCategoryRoute
  '/movies': typeof MoviesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/not-found': typeof NotFoundRoute
  '/movie/$id': typeof MovieIdRoute
  '/movies/$category': typeof MoviesCategoryRoute
  '/movies/': typeof MoviesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/not-found'
    | '/movie/$id'
    | '/movies/$category'
    | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/not-found' | '/movie/$id' | '/movies/$category' | '/movies'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/not-found'
    | '/movie/$id'
    | '/movies/$category'
    | '/movies/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  NotFoundRoute: typeof NotFoundRoute
  MovieIdRoute: typeof MovieIdRoute
  MoviesCategoryRoute: typeof MoviesCategoryRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  NotFoundRoute: NotFoundRoute,
  MovieIdRoute: MovieIdRoute,
  MoviesCategoryRoute: MoviesCategoryRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/not-found",
        "/movie/$id",
        "/movies/$category",
        "/movies/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/movie/$id": {
      "filePath": "movie.$id.tsx"
    },
    "/movies/$category": {
      "filePath": "movies/$category.tsx"
    },
    "/movies/": {
      "filePath": "movies/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
